# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearX

  pod 'ObjectMapper', '3.3'
  pod 'Alamofire', '4.7.2'
  pod 'AlamofireObjectMapper' , '5.0'
  pod 'SwiftyJSON' , '~> 4.2.0'

end
