# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearX


 pod 'Alamofire' , '5.0.0-rc.2'
 pod 'SwiftyJSON'
  
  #  pod 'ObjectMapper'
  #  pod 'AlamofireObjectMapper'
  #  pod 'Validator'


end
